export enum TaskStatus {
  TO_PERFORM = 'TO PERFORM',
  IN_PROGRESS = 'IN PROGRESS',
  READY_FOR_VERIFICATION = 'READY FOR VERIFICATION',
  VERIFICATION_APPROVED = 'VERIFICATION APPROVED',
  DONE = 'DONE',
  FROZEN = 'FROZEN',
  DENIED = 'DENIED'
}
